[package]
name = "funky"
version = "0.1.0"
authors = ["Dominik Süß", "Kevin Per <kevin.per@protonmail.com>"]
edition = "2018"

[workspace]
members = [
	"wasm_parser",
	"validation",
	"from_bits_f64",
	"from_bits_f32"
]

[lib]
path  = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "funky"

[[bin]]
path = "from_bits_f64/src/main.rs"
name = "from_bits_f64"

[[bin]]
path = "from_bits_f32/src/main.rs"
name = "from_bits_f32"

[profile.release]
debug = true

[dependencies]
validation = { path = "./validation" }
wasm-parser = { path = "./wasm_parser" }
env_logger = "0.7"
log = { version = "*", features = ["release_max_level_off"] }
docopt = "1"
serde = { version = "1", features = ["derive"] }
regex = "1"

[dev-dependencies]
insta = "*"
